# Generated by Django 4.1.4 on 2022-12-13 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('D', 'Drama'), ('C', 'Comedy'), ('R', 'Romance'), ('A', 'Action')], default='D', max_length=1)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.director')),
            ],
        ),
    ]
