# Generated by Django 4.1.4 on 2022-12-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_showing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('won', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='showing',
            name='genre',
            field=models.CharField(choices=[('D', 'drama'), ('C', 'comedy'), ('R', 'romance'), ('A', 'action')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='director',
            name='nominations',
            field=models.ManyToManyField(to='main_app.nomination'),
        ),
    ]
